function P = datasetPresets()
%DATASETPRESETS Pipeline terpilih untuk setiap citra dataset resmi.
%   Setiap entri memuat hasil analisis kelompok: masalah citra, metode
%   terpilih (steps), citra referensi (khusus histogram matching), alasan
%   pemilihan, dan metode alternatif yang dibandingkan.
%
%   Path folder/file relatif terhadap folder dataset (default: ./dataset).
%   Preset dapat dimuat di GUI (tombol "Muat preset") lalu diubah bebas.

    S = @makeStep;
    P = struct('folder', {}, 'file', {}, 'problem', {}, 'goal', {}, ...
        'steps', {}, 'ref', {}, 'rationale', {}, 'alternatives', {});

    % ===================== KASUS 1 =====================================
    P(end+1) = entry('2. Kasus 1', 'image_01.png', ...
        'Grayscale (serbuk sari SEM), kontras sangat rendah: intensitas hanya 84-140, std 11. Histogram sempit di tengah.', ...
        'Meningkatkan kontras global agar tekstur permukaan serbuk sari terlihat.', ...
        S('histeq'), '', ...
        ['Histogram sangat sempit dan unimodal -> histogram equalization menyebarkan ' ...
         'level ke seluruh 0-255 (CDF hampir linear), memberi kontras jauh lebih tinggi ' ...
         'dibanding peregangan linear. Tanpa parameter.'], ...
        alt('Contrast stretching 1-99%', S('stretch', [1 99 0 255])));

    P(end+1) = entry('2. Kasus 1', 'image_02.png', ...
        'Foto udara pudar/terlalu terang: mean 196, histogram menumpuk di 180-250, area gelap hampir tidak ada.', ...
        'Memperbaiki kontras dan memisahkan detail bangunan/jalan pada area terang.', ...
        S('histeq'), '', ...
        ['Rentang intensitas sebenarnya lebar (0-255) sehingga stretching tidak berefek; ' ...
         'masalahnya distribusi yang menumpuk di area terang. HE meratakan histogram ' ...
         'sehingga level terang yang padat diregangkan.'], ...
        [alt('Gamma 2.0', S('gamma', [2 1])), alt('Contrast stretching 1-99%', S('stretch', [1 99 0 255]))]);

    P(end+1) = entry('2. Kasus 1', 'image_03.png', ...
        'Citra berwarna (Golden Gate) sedikit berkabut: kontras lokal langit/awan dan bukit rendah, pencahayaan tidak merata.', ...
        'Meningkatkan kontras tanpa merusak warna.', ...
        S('histeq', [], 'ratio'), '', ...
        ['HE pada luminansi meratakan distribusi tone sehingga awan, bukit, dan struktur ' ...
         'jembatan lebih kontras. Luminansi diproses lalu R,G,B diskalakan dengan rasio ' ...
         'Y''/Y agar hue & saturasi tetap (HE per kanal RGB menggeser warna).'], ...
        [alt('Contrast stretching 1-99%', S('stretch', [1 99 0 255], 'ratio')), alt('HE per kanal RGB', S('histeq', [], 'rgb'))]);

    P(end+1) = entry('2. Kasus 1', 'image_04.png', ...
        'Grayscale permukaan bulan, kontras rendah: sebagian besar piksel 58-141, citra terlihat abu-abu datar.', ...
        'Menonjolkan kawah dan relief permukaan.', ...
        S('histeq'), '', ...
        ['Histogram sempit berpuncak tunggal -> HE memberikan penguatan kontras maksimum ' ...
         'dan relief kawah menjadi jelas. Stretching dibandingkan sebagai alternatif (lebih ' ...
         'natural namun kontras lebih rendah).'], ...
        [alt('Contrast stretching 1-99%', S('stretch', [1 99 0 255])), alt('Gamma 0.8 setelah stretching', [S('stretch', [1 99 0 255]), S('gamma', [0.8 1])])]);

    % ===================== KASUS 2 =====================================
    P(end+1) = entry('3. Kasus 2', 'image_01.png', ...
        'Potret grayscale pudar: nilai minimum 79 (tidak ada hitam), mean 170, banyak piksel jenuh 255 di latar.', ...
        'Mengembalikan hitam yang pekat dan menurunkan kecerahan berlebih.', ...
        [S('stretch', [1 99.5 0 255]), S('gamma', [1.6 1])], '', ...
        ['Stretching memetakan level terendah ke 0 (mengembalikan hitam), lalu gamma 1.6 ' ...
         'menggelapkan tone tengah yang terlalu terang. Histogram matching ke Gaussian ' ...
         'menimbulkan posterisasi di latar karena puncak besar di 255.'], ...
        [alt('Histogram matching Gaussian (110, 45)', S('histmatch', [110 45])), ...
         alt('Histogram matching ke Kasus 2/image_02', S('histmatch'), fullfile('3. Kasus 2', 'image_02.png'))]);

    P(end+1) = entry('3. Kasus 2', 'image_02.png', ...
        'Pemandangan grayscale (rumah pedesaan) dengan kontras global cukup, tetapi latar belakang berkabut dan area bayangan gelap.', ...
        'Meningkatkan detail pada latar berkabut dan area bayangan.', ...
        S('histeq'), '', ...
        ['Histogram sudah lebar (std 49) sehingga stretching hampir tidak berefek. HE ' ...
         'meratakan distribusi sehingga latar berkabut dan bayangan lebih kontras ' ...
         '(dengan risiko langit sedikit jenuh).'], ...
        [alt('Contrast stretching 1-99%', S('stretch', [1 99 0 255])), alt('Gamma 0.8', S('gamma', [0.8 1]))]);

    P(end+1) = entry('3. Kasus 2', 'image_03.png', ...
        'Golden Gate dengan warna berlebih: langit biru terlalu jenuh/gelap dan kontras tinggi yang tidak natural.', ...
        'Menyamakan distribusi warna dengan foto referensi yang lebih natural (Kasus 1/image_03).', ...
        S('histmatch', [], 'rgb'), fullfile('2. Kasus 1', 'image_03.png'), ...
        ['Histogram specification per kanal R, G, B terhadap citra referensi dengan ' ...
         'objek yang sama sehingga warna & tone mengikuti referensi.'], ...
        [alt('HE (luminansi)', S('histeq', [], 'ratio')), ...
         alt('Matching luminansi saja', S('histmatch', [], 'ratio'), fullfile('2. Kasus 1', 'image_03.png'))]);

    P(end+1) = entry('3. Kasus 2', 'image_04.png', ...
        'Foto kopi berwarna agak gelap (mean 104) dengan area bayangan kiri atas yang minim detail.', ...
        'Mencerahkan tone gelap sehingga distribusi mendekati Gaussian di tengah.', ...
        S('histmatch', [128 60], 'ratio'), '', ...
        ['Histogram matching ke target Gaussian (mean 128, sigma 60) menggeser massa ' ...
         'histogram ke tengah tanpa meratakan secara ekstrem seperti HE. Diproses pada ' ...
         'luminansi (rasio) agar warna tetap natural.'], ...
        [alt('Gamma 0.8', S('gamma', [0.8 1], 'ratio')), alt('HE global', S('histeq', [], 'ratio'))]);

    % ===================== KASUS 3 =====================================
    P(end+1) = entry('4. Kasus 3', 'image_01.png', ...
        'Lanskap grayscale pudar: intensitas hanya 117-206, kontras rendah.', ...
        'Meregangkan kontras ke seluruh rentang intensitas.', ...
        S('stretch', [0.5 99.8 0 255]), '', ...
        ['Histogram sempit tetapi bentuknya wajar -> peregangan linear memperbesar ' ...
         'kontras tanpa mengubah bentuk distribusi (tone relatif tetap natural).'], ...
        alt('HE global', S('histeq')));

    P(end+1) = entry('4. Kasus 3', 'image_02.png', ...
        'Serbuk sari grayscale, kontras sangat rendah (84-140) (citra sama dengan Kasus 1/image_01).', ...
        'Meningkatkan kontras dengan transformasi intensitas.', ...
        S('stretch', [1 99 0 255]), '', ...
        ['Contrast stretching memberi hasil mendekati HE namun mempertahankan urutan & ' ...
         'proporsi jarak antar level (histogram tidak "bolong-bolong" sebanyak HE).'], ...
        [alt('Log transform', S('log', 0)), alt('HE global', S('histeq'))]);

    P(end+1) = entry('4. Kasus 3', 'image_03.png', ...
        'Interior kantor berwarna sangat pudar/terlalu terang: intensitas 144-213, seperti tertutup kabut putih.', ...
        'Mengembalikan kontras dan kedalaman tone.', ...
        [S('stretch', [1 99 0 255], 'ratio'), S('gamma', [1.3 1], 'ratio')], '', ...
        ['Stretching meregangkan rentang sempit ke 0-255, lalu gamma 1.3 sedikit ' ...
         'menggelapkan tone tengah agar tidak tampak pucat. Mode rasio luminansi menjaga warna.'], ...
        [alt('Stretching saja', S('stretch', [1 99 0 255], 'ratio')), alt('HE (luminansi)', S('histeq', [], 'ratio'))]);

    P(end+1) = entry('4. Kasus 3', 'image_04.png', ...
        'Foto kucing berwarna sangat gelap (underexposed): mean 38, maksimum 73.', ...
        'Mencerahkan citra dan menampilkan detail bulu serta warna mata.', ...
        [S('stretch', [0.5 99.5 0 255], 'ratio'), S('gamma', [0.8 1], 'ratio')], '', ...
        ['Histogram menumpuk di 0-73 -> stretching memetakan ke 0-255, gamma 0.8 ' ...
         'mengangkat tone gelap. Rasio Y''/Y dipakai agar saturasi tidak hilang (proses Y ' ...
         'dengan Cb/Cr tetap membuat citra tampak abu-abu).'], ...
        [alt('Log transform', S('log', 0, 'ratio')), alt('Gamma 0.45', S('gamma', [0.45 1], 'ratio')), ...
         alt('Stretch + gamma (YCbCr)', [S('stretch', [0.5 99.5 0 255], 'ycc'), S('gamma', [0.8 1], 'ycc')])]);

    % ===================== KASUS 4 =====================================
    P(end+1) = entry('5. Kasus 4', 'image_01.png', ...
        'Cameraman grayscale dengan noise salt & pepper (~7% piksel impuls).', ...
        'Menghilangkan noise impuls sambil menjaga tepi.', ...
        S('median', 3), '', ...
        ['Noise impuls -> filter order-statistic. Median 3x3 membuang nilai ekstrem ' ...
         '0/255 dan tetap menjaga tepi (tripod, gedung). Mean filter hanya menyebarkan ' ...
         'impuls menjadi bercak abu-abu.'], ...
        [alt('Median 5x5', S('median', 5)), alt('Mean 3x3 (linear)', S('mean', 3))]);

    P(end+1) = entry('5. Kasus 4', 'image_02.png', ...
        'Potret astronaut berwarna dengan noise salt & pepper padat pada tiap kanal RGB.', ...
        'Menghilangkan noise impuls berwarna.', ...
        S('median', 3, 'rgb'), '', ...
        ['Noise terjadi independen per kanal -> median diterapkan per kanal R,G,B. ' ...
         'Jendela 3x3 sudah menghapus hampir semua impuls; 5x5 lebih bersih namun ' ...
         'detail wajah & tulisan mulai kabur.'], ...
        [alt('Median 5x5 per kanal', S('median', 5, 'rgb')), alt('Mean 3x3 per kanal', S('mean', 3, 'rgb'))]);

    P(end+1) = entry('5. Kasus 4', 'image_03.png', ...
        'Citra koin grayscale dengan noise acak (Gaussian-like), estimasi sigma ~21.', ...
        'Mereduksi noise acak lalu memulihkan kontras koin terhadap latar.', ...
        [S('median', 3), S('gaussian', [5 1]), S('stretch', [1 99 0 255])], '', ...
        ['Median 3x3 meredam komponen noise besar, Gaussian 5x5 (sigma 1) menghaluskan ' ...
         'sisa noise; low-pass sedikit mengurangi kontras sehingga ditutup stretching.'], ...
        [alt('Mean 5x5', S('mean', 5)), alt('Median 5x5', S('median', 5)), alt('Gaussian 5x5 saja', S('gaussian', [5 1]))]);

    P(end+1) = entry('5. Kasus 4', 'image_04.png', ...
        'Tulisan tangan grayscale yang blur (out of focus) dan kontras rendah (45-162).', ...
        'Menajamkan tepi goresan dan meningkatkan kontras tulisan.', ...
        [S('unsharp', [9 3 2]), S('stretch', [0.5 99.5 0 255])], '', ...
        ['Blur lebar -> high-boost dengan mask Gaussian besar (9x9, sigma 3, k=2) ' ...
         'mengembalikan tepi; lalu stretching memperjelas tulisan. Laplacian 3x3 hanya ' ...
         'menajamkan detail halus sehingga kurang efektif untuk blur lebar.'], ...
        [alt('Laplacian alpha 1', [S('laplacian', [1 8]), S('stretch', [0.5 99.5 0 255])]), ...
         alt('Unsharp k=1', [S('unsharp', [5 1 1]), S('stretch', [0.5 99.5 0 255])])]);
end

% -------------------------------------------------------------------------
function e = entry(folder, file, problem, goal, steps, ref, rationale, alternatives)
    e = struct('folder', folder, 'file', file, 'problem', problem, ...
        'goal', goal, 'steps', steps, 'ref', ref, 'rationale', rationale, ...
        'alternatives', alternatives);
end

function a = alt(name, steps, ref)
    if nargin < 3, ref = ''; end
    a = struct('name', name, 'steps', steps, 'ref', ref);
end
